# PostgreSQL + PGAdmin + Node(React) + Node(Express)

# Docker-compose
version: '3'
# Services
services:
  # PostgreSQL - postgres_db
  postgres_db:
    build:
      context: ./
      dockerfile: ./server/postgresql.Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  # API - server
  server:
    build: ./server
    command: npm run start
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - postgres_db
  # UI - client
  client:
    build: ./client
    command: npm run start
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    expose: 
      - ${CLIENT_PORT}
    links:
      - server
  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    links:
      - postgres_db