// Content page
// 
// React 
import React, { Component } from 'react'
// Global-Style Materialize
import Materialize from '../../util/Materialize'
// Content
class Content extends Component {
  // state
  constructor(props) {
    super(props)
    this.state = {
      dashboardPage: true
    }
  }
  // Rrrr
  render() {
    return (
      <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fringilla posuere risus vitae rhoncus. Curabitur ut condimentum nisl. Suspendisse potenti. Sed a aliquet ligula. Mauris libero justo, tempor a metus ac, euismod lacinia ligula. Morbi tincidunt scelerisque leo vitae aliquet. Nulla mattis turpis nulla, ut gravida lorem feugiat id. Vestibulum orci ipsum, pulvinar nec venenatis eu, facilisis at ligula. Sed quis mauris dolor. Morbi sed mauris convallis, scelerisque enim ut, convallis velit. Nam dictum risus nisi, a tempus lorem faucibus ac. Pellentesque ut ultricies mi, ut maximus erat. Nam nec tincidunt sem. Ut efficitur massa lorem, eu sollicitudin lorem accumsan vel. Sed iaculis, arcu sit amet tincidunt tristique, nunc ligula venenatis neque, at consectetur quam elit eu neque.</p>
        <p>Etiam pulvinar, nunc at consequat ullamcorper, erat erat congue metus, sed tempor sapien lorem sit amet massa. Maecenas ut nibh neque. Mauris auctor egestas sapien, et varius quam egestas id. Quisque elementum nulla nec arcu elementum molestie. Sed lectus metus, molestie non tristique non, convallis eu eros. Nulla ultricies eros at ligula rhoncus, eu tempor neque semper. Nulla id urna at lectus eleifend maximus. Donec accumsan justo blandit, semper mi in, accumsan leo. Sed consectetur molestie quam bibendum ultricies. Aliquam erat volutpat. Cras nec diam eu ipsum euismod porta. Fusce tempus nunc pellentesque arcu efficitur, et varius dolor pretium. Sed pulvinar mauris diam, vitae pharetra ante porta ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        <p>Vestibulum ut elit volutpat felis rhoncus rutrum. Suspendisse facilisis sem sed placerat ultrices. Suspendisse iaculis, augue a venenatis mattis, nulla risus vestibulum ligula, sed tristique nisl mauris vitae lorem. Pellentesque posuere dui libero, non accumsan ipsum mollis pellentesque. Pellentesque in eleifend quam. Aenean viverra dui odio, vel sagittis sapien placerat id. Suspendisse congue tincidunt lorem, et tristique dui dapibus a. Mauris non tellus id quam sagittis eleifend in non mauris. Proin sodales tellus tortor, ut tempus leo semper non. Nulla facilisi. Nullam aliquet imperdiet sodales. Maecenas ornare turpis et felis luctus, a blandit magna convallis.</p>
        <p>Sed tincidunt pellentesque leo, eget aliquam odio semper in. Maecenas tincidunt lobortis congue. Integer vitae odio ultrices, convallis dolor et, accumsan erat. Ut venenatis consectetur ligula at gravida. Vivamus eleifend tincidunt elit eu viverra. Duis rutrum elit et sodales fermentum. Nam tempus mauris eu leo sagittis, vel rutrum elit vestibulum. Fusce pretium augue lectus, sed ultricies turpis egestas a. Aliquam viverra risus sed dapibus vestibulum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fringilla posuere risus vitae rhoncus. Curabitur ut condimentum nisl. Suspendisse potenti. Sed a aliquet ligula. Mauris libero justo, tempor a metus ac, euismod lacinia ligula. Morbi tincidunt scelerisque leo vitae aliquet. Nulla mattis turpis nulla, ut gravida lorem feugiat id. Vestibulum orci ipsum, pulvinar nec venenatis eu, facilisis at ligula. Sed quis mauris dolor. Morbi sed mauris convallis, scelerisque enim ut, convallis velit. Nam dictum risus nisi, a tempus lorem faucibus ac. Pellentesque ut ultricies mi, ut maximus erat. Nam nec tincidunt sem. Ut efficitur massa lorem, eu sollicitudin lorem accumsan vel. Sed iaculis, arcu sit amet tincidunt tristique, nunc ligula venenatis neque, at consectetur quam elit eu neque.</p>
        <p>Vestibulum ut elit volutpat felis rhoncus rutrum. Suspendisse facilisis sem sed placerat ultrices. Suspendisse iaculis, augue a venenatis mattis, nulla risus vestibulum ligula, sed tristique nisl mauris vitae lorem. Pellentesque posuere dui libero, non accumsan ipsum mollis pellentesque. Pellentesque in eleifend quam. Aenean viverra dui odio, vel sagittis sapien placerat id. Suspendisse congue tincidunt lorem, et tristique dui dapibus a. Mauris non tellus id quam sagittis eleifend in non mauris. Proin sodales tellus tortor, ut tempus leo semper non. Nulla facilisi. Nullam aliquet imperdiet sodales. Maecenas ornare turpis et felis luctus, a blandit magna convallis.</p>
        <p>Sed tincidunt pellentesque leo, eget aliquam odio semper in. Maecenas tincidunt lobortis congue. Integer vitae odio ultrices, convallis dolor et, accumsan erat. Ut venenatis consectetur ligula at gravida. Vivamus eleifend tincidunt elit eu viverra. Duis rutrum elit et sodales fermentum. Nam tempus mauris eu leo sagittis, vel rutrum elit vestibulum. Fusce pretium augue lectus, sed ultricies turpis egestas a. Aliquam viverra risus sed dapibus vestibulum.</p>
        <p>Maecenas nec congue justo, in egestas lacus. Duis in dignissim enim, nec tincidunt arcu. Duis metus ipsum, convallis quis commodo in, ullamcorper eu leo. Integer consectetur ipsum ut felis efficitur dictum. Sed in dolor orci. Mauris molestie tincidunt lacus a ultrices. Donec quis convallis ex, vel tristique mi. Fusce ut lacus sit amet mi cursus lobortis. Donec fringilla semper arcu a egestas. Curabitur porta erat eu orci scelerisque porta. Nunc id sodales felis. Proin sed tempus mauris, sed ultrices lorem. Vivamus condimentum aliquet consequat. Suspendisse eget libero at nisl eleifend elementum. Integer leo mauris, placerat sed ligula at, faucibus pellentesque sem.</p>
        <p>Sed tincidunt pellentesque leo, eget aliquam odio semper in. Maecenas tincidunt lobortis congue. Integer vitae odio ultrices, convallis dolor et, accumsan erat. Ut venenatis consectetur ligula at gravida. Vivamus eleifend tincidunt elit eu viverra. Duis rutrum elit et sodales fermentum. Nam tempus mauris eu leo sagittis, vel rutrum elit vestibulum. Fusce pretium augue lectus, sed ultricies turpis egestas a. Aliquam viverra risus sed dapibus vestibulum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fringilla posuere risus vitae rhoncus. Curabitur ut condimentum nisl. Suspendisse potenti. Sed a aliquet ligula. Mauris libero justo, tempor a metus ac, euismod lacinia ligula. Morbi tincidunt scelerisque leo vitae aliquet. Nulla mattis turpis nulla, ut gravida lorem feugiat id. Vestibulum orci ipsum, pulvinar nec venenatis eu, facilisis at ligula. Sed quis mauris dolor. Morbi sed mauris convallis, scelerisque enim ut, convallis velit. Nam dictum risus nisi, a tempus lorem faucibus ac. Pellentesque ut ultricies mi, ut maximus erat. Nam nec tincidunt sem. Ut efficitur massa lorem, eu sollicitudin lorem accumsan vel. Sed iaculis, arcu sit amet tincidunt tristique, nunc ligula venenatis neque, at consectetur quam elit eu neque.</p>
        <p>Etiam pulvinar, nunc at consequat ullamcorper, erat erat congue metus, sed tempor sapien lorem sit amet massa. Maecenas ut nibh neque. Mauris auctor egestas sapien, et varius quam egestas id. Quisque elementum nulla nec arcu elementum molestie. Sed lectus metus, molestie non tristique non, convallis eu eros. Nulla ultricies eros at ligula rhoncus, eu tempor neque semper. Nulla id urna at lectus eleifend maximus. Donec accumsan justo blandit, semper mi in, accumsan leo. Sed consectetur molestie quam bibendum ultricies. Aliquam erat volutpat. Cras nec diam eu ipsum euismod porta. Fusce tempus nunc pellentesque arcu efficitur, et varius dolor pretium. Sed pulvinar mauris diam, vitae pharetra ante porta ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fringilla posuere risus vitae rhoncus. Curabitur ut condimentum nisl. Suspendisse potenti. Sed a aliquet ligula. Mauris libero justo, tempor a metus ac, euismod lacinia ligula. Morbi tincidunt scelerisque leo vitae aliquet. Nulla mattis turpis nulla, ut gravida lorem feugiat id. Vestibulum orci ipsum, pulvinar nec venenatis eu, facilisis at ligula. Sed quis mauris dolor. Morbi sed mauris convallis, scelerisque enim ut, convallis velit. Nam dictum risus nisi, a tempus lorem faucibus ac. Pellentesque ut ultricies mi, ut maximus erat. Nam nec tincidunt sem. Ut efficitur massa lorem, eu sollicitudin lorem accumsan vel. Sed iaculis, arcu sit amet tincidunt tristique, nunc ligula venenatis neque, at consectetur quam elit eu neque.</p>
        <p>Vestibulum ut elit volutpat felis rhoncus rutrum. Suspendisse facilisis sem sed placerat ultrices. Suspendisse iaculis, augue a venenatis mattis, nulla risus vestibulum ligula, sed tristique nisl mauris vitae lorem. Pellentesque posuere dui libero, non accumsan ipsum mollis pellentesque. Pellentesque in eleifend quam. Aenean viverra dui odio, vel sagittis sapien placerat id. Suspendisse congue tincidunt lorem, et tristique dui dapibus a. Mauris non tellus id quam sagittis eleifend in non mauris. Proin sodales tellus tortor, ut tempus leo semper non. Nulla facilisi. Nullam aliquet imperdiet sodales. Maecenas ornare turpis et felis luctus, a blandit magna convallis.</p>
        <p>Sed tincidunt pellentesque leo, eget aliquam odio semper in. Maecenas tincidunt lobortis congue. Integer vitae odio ultrices, convallis dolor et, accumsan erat. Ut venenatis consectetur ligula at gravida. Vivamus eleifend tincidunt elit eu viverra. Duis rutrum elit et sodales fermentum. Nam tempus mauris eu leo sagittis, vel rutrum elit vestibulum. Fusce pretium augue lectus, sed ultricies turpis egestas a. Aliquam viverra risus sed dapibus vestibulum.</p>
        {/* Init Materializecss */}
        <Materialize />
      </div>
    );
  }
}
// Bling
export default Content;
